services:
  db:
    image: postgres:16
    container_name: terapi_db
    environment:
      POSTGRES_USER: terapi
      POSTGRES_PASSWORD: terapi_dev
      POSTGRES_DB: terapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: